import { WiringRequest } from 'src/app/core/interfaces/wiring.interface';

export const DATA: WiringRequest[] = [
  {
    id: 'WR1',
    type: 'smf',
    labTeam: 'ec',
    requestingTeam: 'Team1',
    jira: 'JIRA1',
    date: '2023-09-05T14:15:30.252Z',
    status: 'in progress',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        ckid: 'CKID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 2,
          rack: 2,
          unit: 'Unit1',
          name: 'Name11',
          description: 'Description11',
          slot: 'Slot1',
          port: 17,
          portType: 'smf',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 6,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          description: 'Description12',
          slot: 'Slot2',
          port: 38,
          portType: 'mmf',
        },
      },
      {
        id: 'Wiring2',
        notes: 'Notes for wiring 2',
        ckid: 'CKID2',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 2,
          rack: 2,
          unit: 'Unit1',
          name: 'Name11',
          description: 'Description11',
          slot: 'Slot1',
          port: 17,
          portType: 'smf',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 6,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          description: 'Description12',
          slot: 'Slot2',
          port: 38,
          portType: 'mmf',
        },
      },
      {
        id: 'Wiring3',
        notes: 'Notes for wiring 3',
        ckid: 'CKID3',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 2,
          rack: 2,
          unit: 'Unit1',
          name: 'Name11',
          description: 'Description11',
          slot: 'Slot1',
          port: 17,
          portType: 'smf',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 6,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          description: 'Description12',
          slot: 'Slot2',
          port: 38,
          portType: 'mmf',
        },
      },
    ],
  },
];
