import { WiringRequest } from 'src/app/core/interfaces/wiring.interface';

export const DATA: WiringRequest[] = [
  {
    id: 'WR1',
    labTeam: 'ctec',
    requestingTeam: 'Team2',
    jira: 'LABOPS-9858',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'completed',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 4,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 20,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 5,
          rack: 3,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 3,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring2',
        notes: 'Notes for wiring 2',
        circuitId: 'CIRCUITID2',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 4,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 20,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 5,
          rack: 3,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 3,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring3',
        notes: 'Notes for wiring 3',
        circuitId: 'CIRCUITID3',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 4,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 20,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 5,
          rack: 3,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 3,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring4',
        notes: 'Notes for wiring 4',
        circuitId: 'CIRCUITID4',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 4,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 20,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 5,
          rack: 3,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 3,
          portType: 'twinax',
        },
      },
    ],
  },
  {
    id: 'WR2',
    labTeam: 'ctec',
    requestingTeam: 'Team3',
    jira: 'LABOPS-5637',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'queued',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 2,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 36,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 7,
          rack: 3,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 30,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring2',
        notes: 'Notes for wiring 2',
        circuitId: 'CIRCUITID2',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 2,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 36,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 7,
          rack: 3,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 30,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring3',
        notes: 'Notes for wiring 3',
        circuitId: 'CIRCUITID3',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 2,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 36,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 7,
          rack: 3,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 30,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring4',
        notes: 'Notes for wiring 4',
        circuitId: 'CIRCUITID4',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 2,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 36,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 7,
          rack: 3,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 30,
          portType: 'twinax',
        },
      },
    ],
  },
  {
    id: 'WR3',
    labTeam: 'ec',
    requestingTeam: 'Team4',
    jira: 'LABOPS-1075',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'cancelled',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 9,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 28,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 3,
          rack: 5,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 25,
          portType: 'twinax',
        },
      },
    ],
  },
  {
    id: 'WR4',
    labTeam: 'ctec',
    requestingTeam: 'Team4',
    jira: 'LABOPS-9907',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'cancelled',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 7,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 45,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 5,
          rack: 1,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 36,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring2',
        notes: 'Notes for wiring 2',
        circuitId: 'CIRCUITID2',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 7,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 45,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 5,
          rack: 1,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 36,
          portType: 'twinax',
        },
      },
    ],
  },
  {
    id: 'WR5',
    labTeam: 'ctec',
    requestingTeam: 'Team4',
    jira: 'LABOPS-3749',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'queued',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 5,
          rack: 2,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 28,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 10,
          rack: 5,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 3,
          portType: 'twinax',
        },
      },
    ],
  },
  {
    id: 'WR6',
    labTeam: 'ctec',
    requestingTeam: 'Team1',
    jira: 'LABOPS-6917',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'cancelled',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 8,
          rack: 4,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 36,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 4,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 43,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring2',
        notes: 'Notes for wiring 2',
        circuitId: 'CIRCUITID2',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 8,
          rack: 4,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 36,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 4,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 43,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring3',
        notes: 'Notes for wiring 3',
        circuitId: 'CIRCUITID3',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 8,
          rack: 4,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 36,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 4,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 43,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring4',
        notes: 'Notes for wiring 4',
        circuitId: 'CIRCUITID4',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 8,
          rack: 4,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 36,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 4,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 43,
          portType: 'twinax',
        },
      },
    ],
  },
  {
    id: 'WR7',
    labTeam: 'ec',
    requestingTeam: 'Team5',
    jira: 'LABOPS-1719',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'queued',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 7,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 33,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 10,
          rack: 5,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 33,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring2',
        notes: 'Notes for wiring 2',
        circuitId: 'CIRCUITID2',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 7,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 33,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 10,
          rack: 5,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 33,
          portType: 'twinax',
        },
      },
    ],
  },
  {
    id: 'WR8',
    labTeam: 'ctec',
    requestingTeam: 'Team4',
    jira: 'LABOPS-1918',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'cancelled',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 3,
          rack: 3,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 32,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 7,
          rack: 1,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 35,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring2',
        notes: 'Notes for wiring 2',
        circuitId: 'CIRCUITID2',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 3,
          rack: 3,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 32,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 7,
          rack: 1,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 35,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring3',
        notes: 'Notes for wiring 3',
        circuitId: 'CIRCUITID3',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 3,
          rack: 3,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 32,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 7,
          rack: 1,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 35,
          portType: 'twinax',
        },
      },
    ],
  },
  {
    id: 'WR9',
    labTeam: 'ec',
    requestingTeam: 'Team5',
    jira: 'LABOPS-5667',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'cancelled',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 10,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 8,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 10,
          rack: 2,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 9,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring2',
        notes: 'Notes for wiring 2',
        circuitId: 'CIRCUITID2',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 10,
          rack: 5,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 8,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 10,
          rack: 2,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 9,
          portType: 'twinax',
        },
      },
    ],
  },
  {
    id: 'WR10',
    labTeam: 'ctec',
    requestingTeam: 'Team2',
    jira: 'LABOPS-5063',
    date: new Date('2023-09-05T14:44:10.491Z'),
    status: 'completed',
    wiring: [
      {
        id: 'Wiring1',
        notes: 'Notes for wiring 1',
        circuitId: 'CIRCUITID1',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 6,
          rack: 2,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 1,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 9,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 11,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring2',
        notes: 'Notes for wiring 2',
        circuitId: 'CIRCUITID2',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 6,
          rack: 2,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 1,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 9,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 11,
          portType: 'twinax',
        },
      },
      {
        id: 'Wiring3',
        notes: 'Notes for wiring 3',
        circuitId: 'CIRCUITID3',
        from: {
          id: 'WP11',
          pod: 'Pod1',
          row: 6,
          rack: 2,
          unit: 'Unit1',
          name: 'Name11',
          notes: 'Notes11',
          slot: 'Slot1',
          port: 1,
          portType: 'twinax',
        },
        to: {
          id: 'WP12',
          pod: 'Pod1',
          row: 9,
          rack: 4,
          unit: 'Unit2',
          name: 'Name12',
          notes: 'Notes12',
          slot: 'Slot2',
          port: 11,
          portType: 'twinax',
        },
      },
    ],
  },
];
